### all films
GET http://localhost:3000/film

### one films
GET http://localhost:3000/film/3

### add new film
POST http://localhost:3000/film
content-type: application/json

{
    "title": "test",
    "length":122,
    "description":"ejgewghewhgnenwenbwirnbrwnbiwrnbiwr",
    "release_date":"1955-11-10"
}

### update film
PUT http://localhost:3000/film/3
content-type: application/json

{
    "title":"test2",
    "original_title":"test2",
    "length":"234124",
    "description":"egwgegwegwrh",
    "release_date":"1966-11-10",
    "trailer_link":"erghwigiewhigw",
    "parantial_quide":"15"
}